SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `S_CREATE_ROLE` (
	`eventID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`uuid` VARCHAR(64) BINARY DEFAULT '' COMMENT 'new role cookie',
	`rolename` VARCHAR(32) BINARY DEFAULT '' COMMENT 'new role name'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_LOGIN` (
	`eventID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_CONNECT_PLAYER` (
	`eventID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`ip` VARCHAR(32) BINARY DEFAULT '' COMMENT 'connect ip'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_ONLINE_NUMS` (
	`eventID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'online player nums'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_DISCONNECT_PLAYER` (
	`eventID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`ip` VARCHAR(32) BINARY DEFAULT '' COMMENT 'disconnect ip',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_TICK_PLAYER_INFO` (
	`eventID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`id` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`rolename` VARCHAR(32) BINARY DEFAULT '' COMMENT 'role name',
	`job` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'job',
	`sex` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'sex',
	`level` SMALLINT UNSIGNED NOT NULL DEFAULT 0  COMMENT 'level',
	`viplevel` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'viplevel',
	`exp` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'exp',
	`money` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'money',
	`gold` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'now have gold',
	`charge` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'all charge gold'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

