SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE IF NOT EXISTS `S_CREATE_ROLE` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`uuid` VARCHAR(64) BINARY DEFAULT '' COMMENT 'new role cookie',
	`rolename` VARCHAR(32) BINARY DEFAULT '' COMMENT 'new role name'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_LOGIN` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_REQUEST_BUY_INGOT` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`dwChargeNum` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'charge gold num'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_PACKAGE_EXTEND` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`dwNeedCoin` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'use coin',
	`dwNeedGold` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'use gold',
	`dwRoleCoin` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'role coin',
	`dwRoleGold` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'role gold',
	`byCurEquipPkgLimit` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'role equip package max size'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_SELL_ITEMS` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`dwGetCoin` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'get coin by sell',
	`dwRoleCoin` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'role coin',
	`wItemID` SMALLINT UNSIGNED NOT NULL DEFAULT 0  COMMENT 'sell item id',
	`wItemNum` SMALLINT UNSIGNED NOT NULL DEFAULT 0  COMMENT 'sell item number'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_CONFIRM_STRENGTHEN` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`protocal` VARCHAR(32) BINARY DEFAULT '' COMMENT 'protocal type name',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id',
	`dwNeedCoin` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'use coin',
	`dwRoleCoin` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'role coin',
	`wItemID` SMALLINT UNSIGNED NOT NULL DEFAULT 0  COMMENT ' item id',
	`byStrengthLevel` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'item strength level'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_CONNECT_PLAYER` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`ip` VARCHAR(32) BINARY DEFAULT '' COMMENT 'connect ip'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_ONLINE_NUMS` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'online player nums'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `S_DISCONNECT_PLAYER` (
	`eventID` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'event ID',
	`dwTime` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'operate happen time',
	`ip` VARCHAR(32) BINARY DEFAULT '' COMMENT 'disconnect ip',
	`dwRoleID` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mysql role id'
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

