OBJS = listener.o net_util.o read_callback.o

#-DDEBUG 
CXXFLAGS += -DHAVE_CONFIG_H -I$(PRJ_ROOT)/base -I$(LIBEVENT_DIR) -I$(LIBEVENT_DIR)/compat -I$(LIBEVENT_DIR)/include

include ../makefile.common
